markdown: kramdown
highlighter: pygments
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

gems: [jekyll-paginate]
github: infinityhacker
author: "鱼蛋"
email: 825503231@qq.com
name: "梦想无限的大个人博客"
url: http://www.dreaminfinity.cn
domain: www.dreaminfinty.cn
all_categories: [
["android", "渗透","/posts/penetration.html"], 
["program", "html5","/posts/program.html"],
["web", "windows相关","/posts/web.html"], 
["linux", "Linux相关","/posts/linux.html"],
["read", "CSS3","/posts/read.html"], 
["other", "杂记","/posts/other.html"],
["about", "关于","/about.html"]
]

paginate: 8
paginate_path: "posts/page:num"
timezone: America/Los_Angeles

collections:
  docs:
    output: true

gems:
  - jekyll-paginate
